### ISSUE TITLE
Markdown UnicodeDecodeError when .md contains non-ASCII characters.

### ISSUE THREAD

**Issue by dofine** [NoviceLive/urlmark#1]
If there exists non-ascii chars in left.md, e.g. UTF-8 encoded Chinese, program will fail with `UnicodeDecodeError: Markdown only accepts unicode input!`.
System: Windows 7 with Python 2.7. Installed from `pip install`, run `urlmark.exe` directly.

**Comment by NoviceLive** [comment]
Issue reproduced, working on a fix. 

Thanks for reporting.

**Comment by NoviceLive** [comment]
Hi, UrlMark should now be able to normally process files 
encoded in UTF-8 on both Python 2 and Python 3.

You can try the lastest Git version, 
i.e. `pip install git+https://github.com/NoviceLive/urlmark.git`, 
and verify whether this issue is resolved or not.

**Comment by dofine** [comment]
Hi, works perfectly now!
Thanks for the fix!
